services:

  postgres:
    image: postgres:18
    container_name: postgres-iot
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=${DB_PORT}
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql
      - ./infra/data/1-init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./infra/data/2-init.sql:/docker-entrypoint-initdb.d/2-init.sql
      - ./infra/data/3-init.sql:/docker-entrypoint-initdb.d/3-init.sql

  redis:
    image: redis:8-alpine
    container_name: redis-iot
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto-iot
    ports:
      - "${MQTTPORT}:1883"
      - "9001:9001"
    restart: unless-stopped
    volumes:
      - ./infra/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - backend

  simulador-mqtt:
    build:
      context: ./Simulador
      dockerfile: Dockerfile
    container_name: simulador-mqtt-iot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MQTTSERVER=${MQTTSERVER}
      - TOPICS=${TOPICS}
      - SENSORES=${SENSORES}
      - VARIABLES=${VARIABLES}
    depends_on:
      mosquitto:
        condition: service_started
    networks:
      - backend

  mosquitto-service:
    build:
      context: ./mosquitto-service
      dockerfile: Dockerfile
    container_name: mosquitto-service-iot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - PASSWORD_MQ=${PASSWORD_MQ}
      - MQTTSERVER=${MQTTSERVER}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    volumes:
      - ./.env:/app/.env
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  pgdata: